# Generated by Django 4.2.2 on 2023-08-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('icon', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=25)),
                ('address', models.CharField(default='', max_length=150)),
                ('emailid', models.CharField(default='', max_length=150)),
                ('mobileno', models.CharField(default='', max_length=150)),
                ('qualifications', models.CharField(default='', max_length=150)),
                ('password', models.CharField(default='', max_length=100)),
                ('photograph', models.ImageField(upload_to='static/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttimings', models.CharField(default='', max_length=25)),
                ('endtimings', models.CharField(default='', max_length=25)),
                ('days', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.states'),
        ),
        migrations.AddField(
            model_name='city',
            name='states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.states'),
        ),
    ]
