# Generated by Django 4.2.2 on 2023-09-20 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('username', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('emailid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('dob', models.CharField(default='', max_length=200)),
                ('mobileno', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnumber', models.CharField(default='', max_length=200)),
                ('question', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.category')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subquestionnumber', models.CharField(default='', max_length=200)),
                ('subquestion', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.category')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.doctor')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medassistapp.questions')),
            ],
        ),
    ]
